name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fecth-depth: 0
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: |
        docker build -t 12ogelio/graphql-actions:1.0.1 .
        docker build -t 12ogelio/graphql-actions:latest .
    
    - name: Push Docker Image
      run: |
        docker push 12ogelio/graphql-actions:1.0.1
        docker push 12ogelio/graphql-actions:latest
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
